//
// Created by Shadow on 1/19/2025.
//

#ifndef CONFIG_H
#define CONFIG_H
#define MAX_FRAMES_IN_FLIGHT 2
#define MAX_LOADED_MATERIALS 255
#define MAX_LOADED_MATERIAL_INSTANCES 255
#define MAX_LOADED_MESHES 255
#endif //CONFIG_H
